* Wicci Shim

An HTTP reverse-proxy server which bridges between a
client's browser and a PostgreSQL-based [[https://gregdavidson.github.io/wicci-core-S0_lib/][Wicci System]].  A key
component of the NGender Web Framework.

Several Wicci Shims have been written, starting with one
written in C.  The most ambitious is the Wicci-Shim-Rust.
The Rust Shim eschews most of the cost of unsuitable
concurrency, database and web frameworks and libraries and
should eventually replace all others.  Alas, it is far from
done, primarily because of the unsuitability of all of the
existing Rust Web Frameworks!

This Wicci Shim is written in Racket, a remarkably clean and
powerful descendent of Scheme, a modern Lisp.  While this
Shim has more overhead than the Rust Shim in development, it
has nearly all of the desired features with much less code
and complexity.  It is a testament to the extreme flexibility
of the [[https://www.racket-lang.org/][Racket Language]] that their Web Framework
can be used in a manner so different from its original design.
